import XCTest
@testable import Palette

final class PaletteTests: XCTestCase {
    
    func testExample() {
        func testInitOf(color: Color<RGB>, named name: String) {
            let name = name.appending(String(repeating: " ", count: max(20, name.count) - name.count))
            print("Color<RGB>.\(name)", "was successfully initialized.")
        }
        testInitOf(color: .dark, named: "dark")
        testInitOf(color: .marsala, named: "masala")
        testInitOf(color: .roseQuartz, named: "roseQuartz")
        testInitOf(color: .serenity, named: "serenity")
        testInitOf(color: .greenery, named: "greenery")
        testInitOf(color: .ultraviolet, named: "ultraviolet")
        testInitOf(color: .livingCoral, named: "livingCoral")
        testInitOf(color: .classicBlue, named: "classicBlue")
        testInitOf(color: .aliceBlue, named: "aliceBlue")
        testInitOf(color: .antiqueWhite, named: "antiqueWhite")
        testInitOf(color: .aqua, named: "aqua")
        testInitOf(color: .aquamarine, named: "aquamarine")
        testInitOf(color: .azure, named: "azure")
        testInitOf(color: .beige, named: "beige")
        testInitOf(color: .bisque, named: "bisque")
        testInitOf(color: .blanchedAlmond, named: "blanchedAlmond")
        testInitOf(color: .blueViolet, named: "blueViolet")
        testInitOf(color: .brown, named: "brown")
        testInitOf(color: .burlyWood, named: "burlyWood")
        testInitOf(color: .cadetBlue, named: "cadetBlue")
        testInitOf(color: .chartreuse, named: "chartreuse")
        testInitOf(color: .chocolate, named: "chocolate")
        testInitOf(color: .coral, named: "coral")
        testInitOf(color: .cornflowerBlue, named: "cornflowerBlue")
        testInitOf(color: .cornsilk, named: "cornsilk")
        testInitOf(color: .crimson, named: "crimson")
        testInitOf(color: .cyan, named: "cyan")
        testInitOf(color: .darkBlue, named: "darkBlue")
        testInitOf(color: .darkCyan, named: "darkCyan")
        testInitOf(color: .darkGoldenRod, named: "darkGoldenRod")
        testInitOf(color: .darkGray, named: "darkGray")
        testInitOf(color: .darkGreen, named: "darkGreen")
        testInitOf(color: .darkGrey, named: "darkGrey")
        testInitOf(color: .darkKhaki, named: "darkKhaki")
        testInitOf(color: .darkMagenta, named: "darkMagenta")
        testInitOf(color: .darkOliveGreen, named: "darkOliveGreen")
        testInitOf(color: .darkOrange, named: "darkOrange")
        testInitOf(color: .darkOrchid, named: "darkOrchid")
        testInitOf(color: .darkRed, named: "darkRed")
        testInitOf(color: .darkSalmon, named: "darkSalmon")
        testInitOf(color: .darkSeaGreen, named: "darkSeaGreen")
        testInitOf(color: .darkSlateBlue, named: "darkSlateBlue")
        testInitOf(color: .darkSlateGray, named: "darkSlateGray")
        testInitOf(color: .darkSlateGrey, named: "darkSlateGrey")
        testInitOf(color: .darkTurquoise, named: "darkTurquoise")
        testInitOf(color: .darkViolet, named: "darkViolet")
        testInitOf(color: .deepPink, named: "deepPink")
        testInitOf(color: .deepSkyBlue, named: "deepSkyBlue")
        testInitOf(color: .dimGray, named: "dimGray")
        testInitOf(color: .dimGrey, named: "dimGrey")
        testInitOf(color: .dodgerBlue, named: "dodgerBlue")
        testInitOf(color: .fireBrick, named: "fireBrick")
        testInitOf(color: .floralWhite, named: "floralWhite")
        testInitOf(color: .forestGreen, named: "forestGreen")
        testInitOf(color: .gainsboro, named: "gainsboro")
        testInitOf(color: .ghostWhite, named: "ghostWhite")
        testInitOf(color: .gold, named: "gold")
        testInitOf(color: .goldenRod, named: "goldenRod")
        testInitOf(color: .gray, named: "gray")
        testInitOf(color: .greenYellow, named: "greenYellow")
        testInitOf(color: .grey, named: "grey")
        testInitOf(color: .honeyDew, named: "honeyDew")
        testInitOf(color: .hotPink, named: "hotPink")
        testInitOf(color: .indianRed, named: "indianRed")
        testInitOf(color: .indigo, named: "indigo")
        testInitOf(color: .ivory, named: "ivory")
        testInitOf(color: .khaki, named: "khaki")
        testInitOf(color: .lavender, named: "lavender")
        testInitOf(color: .lavenderBlush, named: "lavenderBlush")
        testInitOf(color: .lawnGreen, named: "lawnGreen")
        testInitOf(color: .lemonChiffon, named: "lemonChiffon")
        testInitOf(color: .lightBlue, named: "lightBlue")
        testInitOf(color: .lightCoral, named: "lightCoral")
        testInitOf(color: .lightCyan, named: "lightCyan")
        testInitOf(color: .lightGoldenRodYellow, named: "lightGoldenRodYellow")
        testInitOf(color: .lightGray, named: "lightGray")
        testInitOf(color: .lightGreen, named: "lightGreen")
        testInitOf(color: .lightGrey, named: "lightGrey")
        testInitOf(color: .lightPink, named: "lightPink")
        testInitOf(color: .lightSalmon, named: "lightSalmon")
        testInitOf(color: .lightSeaGreen, named: "lightSeaGreen")
        testInitOf(color: .lightSkyBlue, named: "lightSkyBlue")
        testInitOf(color: .lightSlateGray, named: "lightSlateGray")
        testInitOf(color: .lightSlateGrey, named: "lightSlateGrey")
        testInitOf(color: .lightSteelBlue, named: "lightSteelBlue")
        testInitOf(color: .lightYellow, named: "lightYellow")
        testInitOf(color: .lime, named: "lime")
        testInitOf(color: .limeGreen, named: "limeGreen")
        testInitOf(color: .linen, named: "linen")
        testInitOf(color: .magenta, named: "magenta")
        testInitOf(color: .maroon, named: "maroon")
        testInitOf(color: .mediumAquaMarine, named: "mediumAquaMarine")
        testInitOf(color: .mediumBlue, named: "mediumBlue")
        testInitOf(color: .mediumOrchid, named: "mediumOrchid")
        testInitOf(color: .mediumPurple, named: "mediumPurple")
        testInitOf(color: .mediumSeaGreen, named: "mediumSeaGreen")
        testInitOf(color: .mediumSlateBlue, named: "mediumSlateBlue")
        testInitOf(color: .mediumSpringGreen, named: "mediumSpringGreen")
        testInitOf(color: .mediumTurquoise, named: "mediumTurquoise")
        testInitOf(color: .mediumVioletRed, named: "mediumVioletRed")
        testInitOf(color: .midnightBlue, named: "midnightBlue")
        testInitOf(color: .mintCream, named: "mintCream")
        testInitOf(color: .mistyRose, named: "mistyRose")
        testInitOf(color: .moccasin, named: "moccasin")
        testInitOf(color: .navajoWhite, named: "navajoWhite")
        testInitOf(color: .navy, named: "navy")
        testInitOf(color: .oldLace, named: "oldLace")
        testInitOf(color: .olive, named: "olive")
        testInitOf(color: .oliveDrab, named: "oliveDrab")
        testInitOf(color: .orange, named: "orange")
        testInitOf(color: .orangeRed, named: "orangeRed")
        testInitOf(color: .orchid, named: "orchid")
        testInitOf(color: .paleGoldenRod, named: "paleGoldenRod")
        testInitOf(color: .paleGreen, named: "paleGreen")
        testInitOf(color: .paleTurquoise, named: "paleTurquoise")
        testInitOf(color: .paleVioletRed, named: "paleVioletRed")
        testInitOf(color: .papayaWhip, named: "papayaWhip")
        testInitOf(color: .peachPuff, named: "peachPuff")
        testInitOf(color: .peru, named: "peru")
        testInitOf(color: .pink, named: "pink")
        testInitOf(color: .plum, named: "plum")
        testInitOf(color: .powderBlue, named: "powderBlue")
        testInitOf(color: .purple, named: "purple")
        testInitOf(color: .rebeccaPurple, named: "rebeccaPurple")
        testInitOf(color: .rosyBrown, named: "rosyBrown")
        testInitOf(color: .royalBlue, named: "royalBlue")
        testInitOf(color: .saddleBrown, named: "saddleBrown")
        testInitOf(color: .salmon, named: "salmon")
        testInitOf(color: .sandyBrown, named: "sandyBrown")
        testInitOf(color: .seaGreen, named: "seaGreen")
        testInitOf(color: .seaShell, named: "seaShell")
        testInitOf(color: .sienna, named: "sienna")
        testInitOf(color: .silver, named: "silver")
        testInitOf(color: .skyBlue, named: "skyBlue")
        testInitOf(color: .slateBlue, named: "slateBlue")
        testInitOf(color: .slateGray, named: "slateGray")
        testInitOf(color: .slateGrey, named: "slateGrey")
        testInitOf(color: .snow, named: "snow")
        testInitOf(color: .springGreen, named: "springGreen")
        testInitOf(color: .steelBlue, named: "steelBlue")
        testInitOf(color: .tan , named: "tan ")
        testInitOf(color: .teal, named: "teal")
        testInitOf(color: .thistle, named: "thistle")
        testInitOf(color: .tomato, named: "tomato")
        testInitOf(color: .turquoise, named: "turquoise")
        testInitOf(color: .violet, named: "violet")
        testInitOf(color: .wheat, named: "wheat")
        testInitOf(color: .whiteSmoke, named: "whiteSmoke")
        testInitOf(color: .yellowGreen, named: "yellowGreen")
    }

    static var allTests = [
        ("testExample", testExample),
    ]
}
