import XCTest
@testable import Palette

final class PaletteTests: XCTestCase {
    
    enum MyColorNamespace: CustomColorNamespace {}
    
    func testExample() {
        func testInitOf(color: Color<RGB>, named name: String) {
            let name = name.appending(String(repeating: " ", count: max(20, name.count) - name.count))
            print("Color<RGB>.\(name)", "was successfully initialized.")
        }
        
        testInitOf(color: .pantone(.marsala()), named: "pantone.masala")
        testInitOf(color: .pantone(.roseQuartz()), named: "pantone.roseQuartz")
        testInitOf(color: .pantone(.serenity()), named: "pantone.serenity")
        testInitOf(color: .pantone(.greenery()), named: "pantone.greenery")
        testInitOf(color: .pantone(.ultraviolet()), named: "pantone.ultraviolet")
        testInitOf(color: .pantone(.livingCoral()), named: "pantone.livingCoral")
        testInitOf(color: .pantone(.classicBlue()), named: "pantone.classicBlue")
        
        testInitOf(color: .web(.aliceBlue), named: "web.aliceBlue")
        testInitOf(color: .web(.antiqueWhite), named: "web.antiqueWhite")
        testInitOf(color: .web(.aqua), named: "web.aqua")
        testInitOf(color: .web(.aquamarine), named: "web.aquamarine")
        testInitOf(color: .web(.azure), named: "web.azure")
        testInitOf(color: .web(.beige), named: "web.beige")
        testInitOf(color: .web(.bisque), named: "web.bisque")
        testInitOf(color: .web(.blanchedAlmond), named: "web.blanchedAlmond")
        testInitOf(color: .web(.blueViolet), named: "web.blueViolet")
        testInitOf(color: .web(.brown), named: "web.brown")
        testInitOf(color: .web(.burlyWood), named: "web.burlyWood")
        testInitOf(color: .web(.cadetBlue), named: "web.cadetBlue")
        testInitOf(color: .web(.chartreuse), named: "web.chartreuse")
        testInitOf(color: .web(.chocolate), named: "web.chocolate")
        testInitOf(color: .web(.coral), named: "web.coral")
        testInitOf(color: .web(.cornflowerBlue), named: "web.cornflowerBlue")
        testInitOf(color: .web(.cornsilk), named: "web.cornsilk")
        testInitOf(color: .web(.crimson), named: "web.crimson")
        testInitOf(color: .web(.cyan), named: "web.cyan")
        testInitOf(color: .web(.darkBlue), named: "web.darkBlue")
        testInitOf(color: .web(.darkCyan), named: "web.darkCyan")
        testInitOf(color: .web(.darkGoldenRod), named: "web.darkGoldenRod")
        testInitOf(color: .web(.darkGray), named: "web.darkGray")
        testInitOf(color: .web(.darkGreen), named: "web.darkGreen")
        testInitOf(color: .web(.darkGrey), named: "web.darkGrey")
        testInitOf(color: .web(.darkKhaki), named: "web.darkKhaki")
        testInitOf(color: .web(.darkMagenta), named: "web.darkMagenta")
        testInitOf(color: .web(.darkOliveGreen), named: "web.darkOliveGreen")
        testInitOf(color: .web(.darkOrange), named: "web.darkOrange")
        testInitOf(color: .web(.darkOrchid), named: "web.darkOrchid")
        testInitOf(color: .web(.darkRed), named: "web.darkRed")
        testInitOf(color: .web(.darkSalmon), named: "web.darkSalmon")
        testInitOf(color: .web(.darkSeaGreen), named: "web.darkSeaGreen")
        testInitOf(color: .web(.darkSlateBlue), named: "web.darkSlateBlue")
        testInitOf(color: .web(.darkSlateGray), named: "web.darkSlateGray")
        testInitOf(color: .web(.darkSlateGrey), named: "web.darkSlateGrey")
        testInitOf(color: .web(.darkTurquoise), named: "web.darkTurquoise")
        testInitOf(color: .web(.darkViolet), named: "web.darkViolet")
        testInitOf(color: .web(.deepPink), named: "web.deepPink")
        testInitOf(color: .web(.deepSkyBlue), named: "web.deepSkyBlue")
        testInitOf(color: .web(.dimGray), named: "web.dimGray")
        testInitOf(color: .web(.dimGrey), named: "web.dimGrey")
        testInitOf(color: .web(.dodgerBlue), named: "web.dodgerBlue")
        testInitOf(color: .web(.fireBrick), named: "web.fireBrick")
        testInitOf(color: .web(.floralWhite), named: "web.floralWhite")
        testInitOf(color: .web(.forestGreen), named: "web.forestGreen")
        testInitOf(color: .web(.gainsboro), named: "web.gainsboro")
        testInitOf(color: .web(.ghostWhite), named: "web.ghostWhite")
        testInitOf(color: .web(.gold), named: "web.gold")
        testInitOf(color: .web(.goldenRod), named: "web.goldenRod")
        testInitOf(color: .web(.gray), named: "web.gray")
        testInitOf(color: .web(.greenYellow), named: "web.greenYellow")
        testInitOf(color: .web(.grey), named: "web.grey")
        testInitOf(color: .web(.honeyDew), named: "web.honeyDew")
        testInitOf(color: .web(.hotPink), named: "web.hotPink")
        testInitOf(color: .web(.indianRed), named: "web.indianRed")
        testInitOf(color: .web(.indigo), named: "web.indigo")
        testInitOf(color: .web(.ivory), named: "web.ivory")
        testInitOf(color: .web(.khaki), named: "web.khaki")
        testInitOf(color: .web(.lavender), named: "web.lavender")
        testInitOf(color: .web(.lavenderBlush), named: "web.lavenderBlush")
        testInitOf(color: .web(.lawnGreen), named: "web.lawnGreen")
        testInitOf(color: .web(.lemonChiffon), named: "web.lemonChiffon")
        testInitOf(color: .web(.lightBlue), named: "web.lightBlue")
        testInitOf(color: .web(.lightCoral), named: "web.lightCoral")
        testInitOf(color: .web(.lightCyan), named: "web.lightCyan")
        testInitOf(color: .web(.lightGoldenRodYellow), named: "web.lightGoldenRodYellow")
        testInitOf(color: .web(.lightGray), named: "web.lightGray")
        testInitOf(color: .web(.lightGreen), named: "web.lightGreen")
        testInitOf(color: .web(.lightGrey), named: "web.lightGrey")
        testInitOf(color: .web(.lightPink), named: "web.lightPink")
        testInitOf(color: .web(.lightSalmon), named: "web.lightSalmon")
        testInitOf(color: .web(.lightSeaGreen), named: "web.lightSeaGreen")
        testInitOf(color: .web(.lightSkyBlue), named: "web.lightSkyBlue")
        testInitOf(color: .web(.lightSlateGray), named: "web.lightSlateGray")
        testInitOf(color: .web(.lightSlateGrey), named: "web.lightSlateGrey")
        testInitOf(color: .web(.lightSteelBlue), named: "web.lightSteelBlue")
        testInitOf(color: .web(.lightYellow), named: "web.lightYellow")
        testInitOf(color: .web(.lime), named: "web.lime")
        testInitOf(color: .web(.limeGreen), named: "web.limeGreen")
        testInitOf(color: .web(.linen), named: "web.linen")
        testInitOf(color: .web(.magenta), named: "web.magenta")
        testInitOf(color: .web(.maroon), named: "web.maroon")
        testInitOf(color: .web(.mediumAquaMarine), named: "web.mediumAquaMarine")
        testInitOf(color: .web(.mediumBlue), named: "web.mediumBlue")
        testInitOf(color: .web(.mediumOrchid), named: "web.mediumOrchid")
        testInitOf(color: .web(.mediumPurple), named: "web.mediumPurple")
        testInitOf(color: .web(.mediumSeaGreen), named: "web.mediumSeaGreen")
        testInitOf(color: .web(.mediumSlateBlue), named: "web.mediumSlateBlue")
        testInitOf(color: .web(.mediumSpringGreen), named: "web.mediumSpringGreen")
        testInitOf(color: .web(.mediumTurquoise), named: "web.mediumTurquoise")
        testInitOf(color: .web(.mediumVioletRed), named: "web.mediumVioletRed")
        testInitOf(color: .web(.midnightBlue), named: "web.midnightBlue")
        testInitOf(color: .web(.mintCream), named: "web.mintCream")
        testInitOf(color: .web(.mistyRose), named: "web.mistyRose")
        testInitOf(color: .web(.moccasin), named: "web.moccasin")
        testInitOf(color: .web(.navajoWhite), named: "web.navajoWhite")
        testInitOf(color: .web(.navy), named: "web.navy")
        testInitOf(color: .web(.oldLace), named: "web.oldLace")
        testInitOf(color: .web(.olive), named: "web.olive")
        testInitOf(color: .web(.oliveDrab), named: "web.oliveDrab")
        testInitOf(color: .web(.orange), named: "web.orange")
        testInitOf(color: .web(.orangeRed), named: "web.orangeRed")
        testInitOf(color: .web(.orchid), named: "web.orchid")
        testInitOf(color: .web(.paleGoldenRod), named: "web.paleGoldenRod")
        testInitOf(color: .web(.paleGreen), named: "web.paleGreen")
        testInitOf(color: .web(.paleTurquoise), named: "web.paleTurquoise")
        testInitOf(color: .web(.paleVioletRed), named: "web.paleVioletRed")
        testInitOf(color: .web(.papayaWhip), named: "web.papayaWhip")
        testInitOf(color: .web(.peachPuff), named: "web.peachPuff")
        testInitOf(color: .web(.peru), named: "web.peru")
        testInitOf(color: .web(.pink), named: "web.pink")
        testInitOf(color: .web(.plum), named: "web.plum")
        testInitOf(color: .web(.powderBlue), named: "web.powderBlue")
        testInitOf(color: .web(.purple), named: "web.purple")
        testInitOf(color: .web(.rebeccaPurple), named: "web.rebeccaPurple")
        testInitOf(color: .web(.rosyBrown), named: "web.rosyBrown")
        testInitOf(color: .web(.royalBlue), named: "web.royalBlue")
        testInitOf(color: .web(.saddleBrown), named: "web.saddleBrown")
        testInitOf(color: .web(.salmon), named: "web.salmon")
        testInitOf(color: .web(.sandyBrown), named: "web.sandyBrown")
        testInitOf(color: .web(.seaGreen), named: "web.seaGreen")
        testInitOf(color: .web(.seaShell), named: "web.seaShell")
        testInitOf(color: .web(.sienna), named: "web.sienna")
        testInitOf(color: .web(.silver), named: "web.silver")
        testInitOf(color: .web(.skyBlue), named: "web.skyBlue")
        testInitOf(color: .web(.slateBlue), named: "web.slateBlue")
        testInitOf(color: .web(.slateGray), named: "web.slateGray")
        testInitOf(color: .web(.slateGrey), named: "web.slateGrey")
        testInitOf(color: .web(.snow), named: "web.snow")
        testInitOf(color: .web(.springGreen), named: "web.springGreen")
        testInitOf(color: .web(.steelBlue), named: "web.steelBlue")
        testInitOf(color: .web(.tan ), named: "web.tan ")
        testInitOf(color: .web(.teal), named: "web.teal")
        testInitOf(color: .web(.thistle), named: "web.thistle")
        testInitOf(color: .web(.tomato), named: "web.tomato")
        testInitOf(color: .web(.turquoise), named: "web.turquoise")
        testInitOf(color: .web(.violet), named: "web.violet")
        testInitOf(color: .web(.wheat), named: "web.wheat")
        testInitOf(color: .web(.whiteSmoke), named: "web.whiteSmoke")
        testInitOf(color: .web(.yellowGreen), named: "web.yellowGreen")
        
        testInitOf(color: .iOS(.systemRed()), named: "iOS.systemRed.light")
        testInitOf(color: .iOS(.systemRed(.light)), named: "iOS.systemRed.light")
        testInitOf(color: .iOS(.systemRed(.dark)), named: "iOS.systemRed.dark")
        
        testInitOf(color: .iOS(.systemOrange()), named: "iOS.systemOrange.light")
        testInitOf(color: .iOS(.systemOrange(.light)), named: "iOS.systemOrange.light")
        testInitOf(color: .iOS(.systemOrange(.dark)), named: "iOS.systemOrange.dark")
        
        testInitOf(color: .iOS(.systemYellow()), named: "iOS.systemYellow.light")
        testInitOf(color: .iOS(.systemYellow(.light)), named: "iOS.systemYellow.light")
        testInitOf(color: .iOS(.systemYellow(.dark)), named: "iOS.systemYellow.dark")
        
        testInitOf(color: .iOS(.systemGreen()), named: "iOS.systemGreen.light")
        testInitOf(color: .iOS(.systemGreen(.light)), named: "iOS.systemGreen.light")
        testInitOf(color: .iOS(.systemGreen(.dark)), named: "iOS.systemGreen.dark")
        
        testInitOf(color: .iOS(.systemTeal()), named: "iOS.systemTeal.light")
        testInitOf(color: .iOS(.systemTeal(.light)), named: "iOS.systemTeal.light")
        testInitOf(color: .iOS(.systemTeal(.dark)), named: "iOS.systemTeal.dark")
        
        testInitOf(color: .iOS(.systemBlue()), named: "iOS.systemBlue.light")
        testInitOf(color: .iOS(.systemBlue(.light)), named: "iOS.systemBlue.light")
        testInitOf(color: .iOS(.systemBlue(.dark)), named: "iOS.systemBlue.dark")
        
        testInitOf(color: .iOS(.systemIndigo()), named: "iOS.systemIndigo.light")
        testInitOf(color: .iOS(.systemIndigo(.light)), named: "iOS.systemIndigo.light")
        testInitOf(color: .iOS(.systemIndigo(.dark)), named: "iOS.systemIndigo.dark")
        
        testInitOf(color: .iOS(.systemPurple()), named: "iOS.systemPurple.light")
        testInitOf(color: .iOS(.systemPurple(.light)), named: "iOS.systemPurple.light")
        testInitOf(color: .iOS(.systemPurple(.dark)), named: "iOS.systemPurple.dark")
        
        testInitOf(color: .iOS(.systemPink()), named: "iOS.systemPink.light")
        testInitOf(color: .iOS(.systemPink(.light)), named: "iOS.systemPink.light")
        testInitOf(color: .iOS(.systemPink(.dark)), named: "iOS.systemPink.dark")
        
        testInitOf(color: .iOS(.systemGrey()), named: "iOS.systemGrey.light")
        testInitOf(color: .iOS(.systemGrey(.light)), named: "iOS.systemGrey.light")
        testInitOf(color: .iOS(.systemGrey(.dark)), named: "iOS.systemGrey.dark")
        
        testInitOf(color: .iOS(.systemGrey2()), named: "iOS.systemGrey2.light")
        testInitOf(color: .iOS(.systemGrey2(.light)), named: "iOS.systemGrey2.light")
        testInitOf(color: .iOS(.systemGrey2(.dark)), named: "iOS.systemGrey2.dark")
        
        testInitOf(color: .iOS(.systemGrey3()), named: "iOS.systemGrey3.light")
        testInitOf(color: .iOS(.systemGrey3(.light)), named: "iOS.systemGrey3.light")
        testInitOf(color: .iOS(.systemGrey3(.dark)), named: "iOS.systemGrey3.dark")
        
        testInitOf(color: .iOS(.systemGrey4()), named: "iOS.systemGrey4.light")
        testInitOf(color: .iOS(.systemGrey4(.light)), named: "iOS.systemGrey4.light")
        testInitOf(color: .iOS(.systemGrey4(.dark)), named: "iOS.systemGrey4.dark")
        
        testInitOf(color: .iOS(.systemGrey5()), named: "iOS.systemGrey5.light")
        testInitOf(color: .iOS(.systemGrey5(.light)), named: "iOS.systemGrey5.light")
        testInitOf(color: .iOS(.systemGrey5(.dark)), named: "iOS.systemGrey5.dark")
        
        testInitOf(color: .iOS(.systemGrey6()), named: "iOS.systemGrey6.light")
        testInitOf(color: .iOS(.systemGrey6(.light)), named: "iOS.systemGrey6.light")
        testInitOf(color: .iOS(.systemGrey6(.dark)), named: "iOS.systemGrey6.dark")
        
        testInitOf(color: .iOS(.systemDisabled()), named: "iOS.systemDisabled.light")
        testInitOf(color: .iOS(.systemDisabled(.light)), named: "iOS.systemDisabled.light")
        testInitOf(color: .iOS(.systemDisabled(.dark)), named: "iOS.systemDisabled.dark")
        
    }

    static var allTests = [
        ("testExample", testExample),
    ]
}
